=== zchar007/eclipse_apps/SmartCopy2.0/xml/bean.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.w3school.com.cn"
	xmlns="http://www.w3school.com.cn" elementFormDefault="qualified">
	<xs:element name="beans">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="bean" maxOccurs="unbounded"
					minOccurs="1"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="bean">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" minOccurs="0"></xs:element>
				<xs:element ref="content" minOccurs="0" maxOccurs="1"></xs:element>
				<xs:element ref="description" minOccurs="0" maxOccurs="1"></xs:element>
				<xs:element ref="steps" minOccurs="0" maxOccurs="1"></xs:element>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="name" type="xs:string"
				use="required" />
			<xs:attribute name="class" type="xs:string"
				use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="import" type="xs:string"></xs:element>
	<xs:element name="content" type="xs:string"></xs:element>
	<xs:element name="description" type="xs:string"></xs:element>
	<!-- 自定义步骤的根目录 -->
	<xs:element name="steps" type="elementType" />
	<!-- 定义参数值 -->
	<xs:element name="define">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string"
				use="required" />
			<xs:attribute name="value" type="xs:string"
				use="required" />
			<xs:attribute name="type" type="vartype" use="optional" />
		</xs:complexType>
	</xs:element>
	<!-- ifelse -->
	<xs:element name="if">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="define" minOccurs="0"
					maxOccurs="unbounded"></xs:element>
				<xs:element ref="if" minOccurs="0" maxOccurs="unbounded"></xs:element>
				<xs:element ref="loop" minOccurs="0"
					maxOccurs="unbounded"></xs:element>
				<xs:element ref="tool" minOccurs="0"
					maxOccurs="unbounded"></xs:element>
				<xs:element ref="append" minOccurs="0"
					maxOccurs="unbounded"></xs:element>
			</xs:choice>
			<xs:attribute name="apara" type="xs:string"
				use="required" />
			<xs:attribute name="bpara" type="xs:string"
				use="required" />
			<xs:attribute name="compare" type="comparetype"
				use="required" />
		</xs:complexType>
	</xs:element>
	<!-- 循环 -->
	<xs:element name="loop">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="define" minOccurs="0"
					maxOccurs="unbounded"></xs:element>
				<xs:element ref="if" minOccurs="0" maxOccurs="unbounded"></xs:element>
				<xs:element ref="loop" minOccurs="0"
					maxOccurs="unbounded"></xs:element>
				<xs:element ref="tool" minOccurs="0"
					maxOccurs="unbounded"></xs:element>
				<xs:element ref="append" minOccurs="0"
					maxOccurs="unbounded"></xs:element>
			</xs:choice>
			<xs:attribute name="loopVar" type="xs:string"
				use="optional" />
			<xs:attribute name="stepVar" type="xs:string"
				use="required" />
			<xs:attribute name="beginIndex" type="xs:int"
				use="required" />
			<xs:attribute name="endIndex" type="xs:string"
				use="required" />
		</xs:complexType>
	</xs:element>
	<!-- 调用stringutil默认提供的方法，入参为数组或字符串，出参同样 -->
	<xs:element name="tool">
		<xs:complexType>
			<xs:attribute name="toolName" type="tooltype"
				use="required" />
			<xs:attribute name="name" type="xs:string"
				use="required" />
			<xs:attribute name="value" type="xs:string"
				use="required" />
			<xs:attribute name="regex" type="xs:string"
				use="optional" />
			<xs:attribute name="beginIndex" type="xs:int"
				use="optional" />
			<xs:attribute name="endIndex" type="xs:int"
				use="optional" />
		</xs:complexType>
	</xs:element>
	<!-- 添加字符串到输出流中 -->
	<xs:element name="append">
		<xs:complexType>
			<xs:attribute name="value" type="xs:string"
				use="required" />
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="vartype">
		<xs:restriction base="xs:string">
			<xs:enumeration value="string" />
			<xs:enumeration value="array" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tooltype">
		<xs:restriction base="xs:string">
			<xs:enumeration value="sub" />
			<xs:enumeration value="split" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="comparetype">
		<xs:restriction base="xs:string">
			<xs:enumeration value="EQ" />
			<xs:enumeration value="NEQ" />
			<xs:enumeration value="BIG" />
			<xs:enumeration value="MIN" />
			<xs:enumeration value="BIGEQ" />
			<xs:enumeration value="MINEQ" />
			<xs:enumeration value="CONTAINS" />
			<xs:enumeration value="STARTWITH" />
			<xs:enumeration value="ENDWITH" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="elementType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="define" minOccurs="0"
				maxOccurs="unbounded"></xs:element>
			<xs:element ref="if" minOccurs="0" maxOccurs="unbounded"></xs:element>
			<xs:element ref="loop" minOccurs="0" maxOccurs="unbounded"></xs:element>
			<xs:element ref="tool" minOccurs="0" maxOccurs="unbounded"></xs:element>
			<xs:element ref="append" minOccurs="0"
				maxOccurs="unbounded"></xs:element>
		</xs:choice>
	</xs:complexType>
</xs:schema>

=== zchar007/eclipse_apps/SmartCopy2.0/xml/demo2.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.w3school.com.cn"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3school.com.cn bean.xsd">
	<bean id="DemoRealize" name="AB归类器">
		<content> String[] messages = message.split(&quot;,&quot;);
			String aStr
			= &quot;&quot;, bStr = &quot;&quot;;
			for (int i = 0; i &lt;
			messages.length; i++) {
			if
			(messages[i].startsWith(&quot;a&quot;)) {
			aStr+=messages[i];
			}
			if (messages[i].startsWith(&quot;b&quot;)) {
			bStr+=messages[i];
			}
			}
			return
			&quot;A:[&quot;+aStr+&quot;]B:[&quot;+bStr+&quot;]&quot;;
		</content>
	</bean>
	<bean id="DemoRealize2" name="AB归类器2"
		class="classz/DemoRealize.class" />
	<bean name="测试1" id="test1">
		<description>测试的Steps配置</description>
		<steps>
			<define name="name" value="张三" />
			<define name="class" value="语文,数学,英语" />
			<tool name="classs" toolName="split" value="${class}" />
			<tool name="greads" value="120,111,130" toolName="split" />
			<append value="姓名：${name}\n" />
			<loop beginIndex="0" endIndex="3" stepVar="index">
				<append value="${classs[index]}成绩是${greads[index]}\n" />
			</loop>
			<append value="老师：${@input}" />
		</steps>
	</bean>
	<bean name="测试2" id="test2">
		<description>测试的Steps配置</description>
		<steps>
			<define name="name" value="张三" />
			<define name="class" value="语文,数学,英语" />
			<tool name="classs" toolName="split" value="${class}" />
			<tool name="greads" value="120,111,130" toolName="split" />
			<append value="姓名：${name}\n" />
			<if bpara="语文" compare="EQ" apara="@input">
				<append value="${classs[0]}成绩是${greads[0]}" />
			</if>
			<if bpara="数学" compare="EQ" apara="@input">
				<append value="${classs[1]}成绩是${greads[1]}" />
			</if>
			<if bpara="英语" compare="EQ" apara="@input">
				<append value="${classs[2]}成绩是${greads[2]}" />
			</if>
		</steps>
	</bean>
	<bean name="Sql-Java" id="sqltojava">
		<description>sql转乘append形式的java</description>
		<steps>
			<tool name="slqs" toolName="split" value="@input"
				regex="&#x000A;" />
			<append
				value="StringBuilder sqlBF = new StringBuilder();&#x000A;" />
			<append value="sqlBF.setLength(0);&#x000A;" />
			<loop beginIndex="0" endIndex="n" stepVar="sql"
				loopVar="${slqs}">
				<append value="sqlBF.append(&quot;${sql}&quot;);&#x000A;" />
			</loop>
			<append value="this.sql.setSql(sqlBF);&#x000A;" />
		</steps>
	</bean>
</beans>
